// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apsrxxucmzqypoanaqoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwc3J4eHVjbXpxeXBvYW5hcW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMTQ2NzEsImV4cCI6MjA1ODY5MDY3MX0.7Dcjw4IlIAHshRXUB-Pah-DhPXdlB3w0zLymP1n5oBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);